/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing ListWishlistsRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListWishlistsRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListWishlistsRequestFilter
        //private ListWishlistsRequestFilter instance;

        public ListWishlistsRequestFilterTests()
        {
            // TODO uncomment below to create an instance of ListWishlistsRequestFilter
            //instance = new ListWishlistsRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListWishlistsRequestFilter
        /// </summary>
        [Fact]
        public void ListWishlistsRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListWishlistsRequestFilter
            //Assert.IsType<ListWishlistsRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }
    }
}
