/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistUpdateWishlistRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistUpdateWishlistRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistUpdateWishlistRequestPayload
        //private WishlistUpdateWishlistRequestPayload instance;

        public WishlistUpdateWishlistRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of WishlistUpdateWishlistRequestPayload
            //instance = new WishlistUpdateWishlistRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistUpdateWishlistRequestPayload
        /// </summary>
        [Fact]
        public void WishlistUpdateWishlistRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistUpdateWishlistRequestPayload
            //Assert.IsType<WishlistUpdateWishlistRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
    }
}
