/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistPermission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistPermissionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistPermission
        //private WishlistPermission instance;

        public WishlistPermissionTests()
        {
            // TODO uncomment below to create an instance of WishlistPermission
            //instance = new WishlistPermission();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistPermission
        /// </summary>
        [Fact]
        public void WishlistPermissionInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistPermission
            //Assert.IsType<WishlistPermission>(instance);
        }
    }
}
