/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistAreItemsInWishlistsResponsePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistAreItemsInWishlistsResponsePayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistAreItemsInWishlistsResponsePayload
        //private WishlistAreItemsInWishlistsResponsePayload instance;

        public WishlistAreItemsInWishlistsResponsePayloadTests()
        {
            // TODO uncomment below to create an instance of WishlistAreItemsInWishlistsResponsePayload
            //instance = new WishlistAreItemsInWishlistsResponsePayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistAreItemsInWishlistsResponsePayload
        /// </summary>
        [Fact]
        public void WishlistAreItemsInWishlistsResponsePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistAreItemsInWishlistsResponsePayload
            //Assert.IsType<WishlistAreItemsInWishlistsResponsePayload>(instance);
        }

        /// <summary>
        /// Test the property 'WishlistGrnToWishlistItemGrnMap'
        /// </summary>
        [Fact]
        public void WishlistGrnToWishlistItemGrnMapTest()
        {
            // TODO unit test for the property 'WishlistGrnToWishlistItemGrnMap'
        }
    }
}
