/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistListWishlistsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistListWishlistsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistListWishlistsResponse
        //private WishlistListWishlistsResponse instance;

        public WishlistListWishlistsResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistListWishlistsResponse
            //instance = new WishlistListWishlistsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistListWishlistsResponse
        /// </summary>
        [Fact]
        public void WishlistListWishlistsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistListWishlistsResponse
            //Assert.IsType<WishlistListWishlistsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Wishlist'
        /// </summary>
        [Fact]
        public void WishlistTest()
        {
            // TODO unit test for the property 'Wishlist'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
