/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistAddItemToWishlistRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistAddItemToWishlistRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistAddItemToWishlistRequest
        //private WishlistAddItemToWishlistRequest instance;

        public WishlistAddItemToWishlistRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistAddItemToWishlistRequest
            //instance = new WishlistAddItemToWishlistRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistAddItemToWishlistRequest
        /// </summary>
        [Fact]
        public void WishlistAddItemToWishlistRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistAddItemToWishlistRequest
            //Assert.IsType<WishlistAddItemToWishlistRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'WishlistId'
        /// </summary>
        [Fact]
        public void WishlistIdTest()
        {
            // TODO unit test for the property 'WishlistId'
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'PreferredQuantity'
        /// </summary>
        [Fact]
        public void PreferredQuantityTest()
        {
            // TODO unit test for the property 'PreferredQuantity'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }
    }
}
