/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistSharingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistSharingResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistSharingResponse
        //private WishlistSharingResponse instance;

        public WishlistSharingResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistSharingResponse
            //instance = new WishlistSharingResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistSharingResponse
        /// </summary>
        [Fact]
        public void WishlistSharingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistSharingResponse
            //Assert.IsType<WishlistSharingResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SharingId'
        /// </summary>
        [Fact]
        public void SharingIdTest()
        {
            // TODO unit test for the property 'SharingId'
        }

        /// <summary>
        /// Test the property 'SharingGrn'
        /// </summary>
        [Fact]
        public void SharingGrnTest()
        {
            // TODO unit test for the property 'SharingGrn'
        }

        /// <summary>
        /// Test the property 'WishlistId'
        /// </summary>
        [Fact]
        public void WishlistIdTest()
        {
            // TODO unit test for the property 'WishlistId'
        }

        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Fact]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }

        /// <summary>
        /// Test the property 'CustomerAggregationId'
        /// </summary>
        [Fact]
        public void CustomerAggregationIdTest()
        {
            // TODO unit test for the property 'CustomerAggregationId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
