/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistGetItemFromWishlistRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistGetItemFromWishlistRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistGetItemFromWishlistRequest
        //private WishlistGetItemFromWishlistRequest instance;

        public WishlistGetItemFromWishlistRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistGetItemFromWishlistRequest
            //instance = new WishlistGetItemFromWishlistRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistGetItemFromWishlistRequest
        /// </summary>
        [Fact]
        public void WishlistGetItemFromWishlistRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistGetItemFromWishlistRequest
            //Assert.IsType<WishlistGetItemFromWishlistRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
