/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistWishlistItemResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistWishlistItemResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistWishlistItemResponse
        //private WishlistWishlistItemResponse instance;

        public WishlistWishlistItemResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistWishlistItemResponse
            //instance = new WishlistWishlistItemResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistWishlistItemResponse
        /// </summary>
        [Fact]
        public void WishlistWishlistItemResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistWishlistItemResponse
            //Assert.IsType<WishlistWishlistItemResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'WishlistId'
        /// </summary>
        [Fact]
        public void WishlistIdTest()
        {
            // TODO unit test for the property 'WishlistId'
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'PreferredQuantity'
        /// </summary>
        [Fact]
        public void PreferredQuantityTest()
        {
            // TODO unit test for the property 'PreferredQuantity'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'AddedByCustomerGrn'
        /// </summary>
        [Fact]
        public void AddedByCustomerGrnTest()
        {
            // TODO unit test for the property 'AddedByCustomerGrn'
        }

        /// <summary>
        /// Test the property 'AddedAt'
        /// </summary>
        [Fact]
        public void AddedAtTest()
        {
            // TODO unit test for the property 'AddedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
