/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistBulkRevokeSharingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistBulkRevokeSharingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistBulkRevokeSharingRequest
        //private WishlistBulkRevokeSharingRequest instance;

        public WishlistBulkRevokeSharingRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistBulkRevokeSharingRequest
            //instance = new WishlistBulkRevokeSharingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistBulkRevokeSharingRequest
        /// </summary>
        [Fact]
        public void WishlistBulkRevokeSharingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistBulkRevokeSharingRequest
            //Assert.IsType<WishlistBulkRevokeSharingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SharingIds'
        /// </summary>
        [Fact]
        public void SharingIdsTest()
        {
            // TODO unit test for the property 'SharingIds'
        }
    }
}
