/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistMergeWishlistsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistMergeWishlistsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistMergeWishlistsRequest
        //private WishlistMergeWishlistsRequest instance;

        public WishlistMergeWishlistsRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistMergeWishlistsRequest
            //instance = new WishlistMergeWishlistsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistMergeWishlistsRequest
        /// </summary>
        [Fact]
        public void WishlistMergeWishlistsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistMergeWishlistsRequest
            //Assert.IsType<WishlistMergeWishlistsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'StartingWishlistId'
        /// </summary>
        [Fact]
        public void StartingWishlistIdTest()
        {
            // TODO unit test for the property 'StartingWishlistId'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }

        /// <summary>
        /// Test the property 'TargetWishlistId'
        /// </summary>
        [Fact]
        public void TargetWishlistIdTest()
        {
            // TODO unit test for the property 'TargetWishlistId'
        }
    }
}
