/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistListWishlistItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistListWishlistItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistListWishlistItemsResponse
        //private WishlistListWishlistItemsResponse instance;

        public WishlistListWishlistItemsResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistListWishlistItemsResponse
            //instance = new WishlistListWishlistItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistListWishlistItemsResponse
        /// </summary>
        [Fact]
        public void WishlistListWishlistItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistListWishlistItemsResponse
            //Assert.IsType<WishlistListWishlistItemsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'WishlistItems'
        /// </summary>
        [Fact]
        public void WishlistItemsTest()
        {
            // TODO unit test for the property 'WishlistItems'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
