/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistBulkCreateSharingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistBulkCreateSharingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistBulkCreateSharingRequest
        //private WishlistBulkCreateSharingRequest instance;

        public WishlistBulkCreateSharingRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistBulkCreateSharingRequest
            //instance = new WishlistBulkCreateSharingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistBulkCreateSharingRequest
        /// </summary>
        [Fact]
        public void WishlistBulkCreateSharingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistBulkCreateSharingRequest
            //Assert.IsType<WishlistBulkCreateSharingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SharingRequests'
        /// </summary>
        [Fact]
        public void SharingRequestsTest()
        {
            // TODO unit test for the property 'SharingRequests'
        }
    }
}
