/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistUpdateItemInWishlistRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistUpdateItemInWishlistRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistUpdateItemInWishlistRequestPayload
        //private WishlistUpdateItemInWishlistRequestPayload instance;

        public WishlistUpdateItemInWishlistRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of WishlistUpdateItemInWishlistRequestPayload
            //instance = new WishlistUpdateItemInWishlistRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistUpdateItemInWishlistRequestPayload
        /// </summary>
        [Fact]
        public void WishlistUpdateItemInWishlistRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistUpdateItemInWishlistRequestPayload
            //Assert.IsType<WishlistUpdateItemInWishlistRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'PreferredQuantity'
        /// </summary>
        [Fact]
        public void PreferredQuantityTest()
        {
            // TODO unit test for the property 'PreferredQuantity'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }
    }
}
