/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistSharingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistSharingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistSharingRequest
        //private WishlistSharingRequest instance;

        public WishlistSharingRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistSharingRequest
            //instance = new WishlistSharingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistSharingRequest
        /// </summary>
        [Fact]
        public void WishlistSharingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistSharingRequest
            //Assert.IsType<WishlistSharingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'WishlistId'
        /// </summary>
        [Fact]
        public void WishlistIdTest()
        {
            // TODO unit test for the property 'WishlistId'
        }

        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Fact]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }

        /// <summary>
        /// Test the property 'CustomerAggregationId'
        /// </summary>
        [Fact]
        public void CustomerAggregationIdTest()
        {
            // TODO unit test for the property 'CustomerAggregationId'
        }
    }
}
