/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistBulkCreateSharingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistBulkCreateSharingResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistBulkCreateSharingResponse
        //private WishlistBulkCreateSharingResponse instance;

        public WishlistBulkCreateSharingResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistBulkCreateSharingResponse
            //instance = new WishlistBulkCreateSharingResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistBulkCreateSharingResponse
        /// </summary>
        [Fact]
        public void WishlistBulkCreateSharingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistBulkCreateSharingResponse
            //Assert.IsType<WishlistBulkCreateSharingResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SharingResponses'
        /// </summary>
        [Fact]
        public void SharingResponsesTest()
        {
            // TODO unit test for the property 'SharingResponses'
        }
    }
}
