/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistAreItemsInWishlistsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistAreItemsInWishlistsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistAreItemsInWishlistsRequest
        //private WishlistAreItemsInWishlistsRequest instance;

        public WishlistAreItemsInWishlistsRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistAreItemsInWishlistsRequest
            //instance = new WishlistAreItemsInWishlistsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistAreItemsInWishlistsRequest
        /// </summary>
        [Fact]
        public void WishlistAreItemsInWishlistsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistAreItemsInWishlistsRequest
            //Assert.IsType<WishlistAreItemsInWishlistsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'WishlistId'
        /// </summary>
        [Fact]
        public void WishlistIdTest()
        {
            // TODO unit test for the property 'WishlistId'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }

        /// <summary>
        /// Test the property 'ItemGrns'
        /// </summary>
        [Fact]
        public void ItemGrnsTest()
        {
            // TODO unit test for the property 'ItemGrns'
        }
    }
}
