/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistWishlistResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistWishlistResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistWishlistResponse
        //private WishlistWishlistResponse instance;

        public WishlistWishlistResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistWishlistResponse
            //instance = new WishlistWishlistResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistWishlistResponse
        /// </summary>
        [Fact]
        public void WishlistWishlistResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistWishlistResponse
            //Assert.IsType<WishlistWishlistResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'SharedCode'
        /// </summary>
        [Fact]
        public void SharedCodeTest()
        {
            // TODO unit test for the property 'SharedCode'
        }

        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'ItemsCount'
        /// </summary>
        [Fact]
        public void ItemsCountTest()
        {
            // TODO unit test for the property 'ItemsCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
