/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistGetWishlistBySharedCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistGetWishlistBySharedCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistGetWishlistBySharedCodeRequest
        //private WishlistGetWishlistBySharedCodeRequest instance;

        public WishlistGetWishlistBySharedCodeRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistGetWishlistBySharedCodeRequest
            //instance = new WishlistGetWishlistBySharedCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistGetWishlistBySharedCodeRequest
        /// </summary>
        [Fact]
        public void WishlistGetWishlistBySharedCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistGetWishlistBySharedCodeRequest
            //Assert.IsType<WishlistGetWishlistBySharedCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SharedCode'
        /// </summary>
        [Fact]
        public void SharedCodeTest()
        {
            // TODO unit test for the property 'SharedCode'
        }

        /// <summary>
        /// Test the property 'CustomerGrn'
        /// </summary>
        [Fact]
        public void CustomerGrnTest()
        {
            // TODO unit test for the property 'CustomerGrn'
        }
    }
}
