/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistAreItemsInWishlistsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistAreItemsInWishlistsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistAreItemsInWishlistsResponse
        //private WishlistAreItemsInWishlistsResponse instance;

        public WishlistAreItemsInWishlistsResponseTests()
        {
            // TODO uncomment below to create an instance of WishlistAreItemsInWishlistsResponse
            //instance = new WishlistAreItemsInWishlistsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistAreItemsInWishlistsResponse
        /// </summary>
        [Fact]
        public void WishlistAreItemsInWishlistsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistAreItemsInWishlistsResponse
            //Assert.IsType<WishlistAreItemsInWishlistsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ItemGrnMap'
        /// </summary>
        [Fact]
        public void ItemGrnMapTest()
        {
            // TODO unit test for the property 'ItemGrnMap'
        }
    }
}
