/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistLocalizedText
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistLocalizedTextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistLocalizedText
        //private WishlistLocalizedText instance;

        public WishlistLocalizedTextTests()
        {
            // TODO uncomment below to create an instance of WishlistLocalizedText
            //instance = new WishlistLocalizedText();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistLocalizedText
        /// </summary>
        [Fact]
        public void WishlistLocalizedTextInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistLocalizedText
            //Assert.IsType<WishlistLocalizedText>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
