/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistUpdateWishlistRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistUpdateWishlistRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistUpdateWishlistRequest
        //private WishlistUpdateWishlistRequest instance;

        public WishlistUpdateWishlistRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistUpdateWishlistRequest
            //instance = new WishlistUpdateWishlistRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistUpdateWishlistRequest
        /// </summary>
        [Fact]
        public void WishlistUpdateWishlistRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistUpdateWishlistRequest
            //Assert.IsType<WishlistUpdateWishlistRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'PayloadMask'
        /// </summary>
        [Fact]
        public void PayloadMaskTest()
        {
            // TODO unit test for the property 'PayloadMask'
        }
    }
}
