/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using wishlist.Model;
using wishlist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace wishlist.Test.Model
{
    /// <summary>
    ///  Class for testing WishlistBulkRemoveItemsFromWishlistsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WishlistBulkRemoveItemsFromWishlistsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WishlistBulkRemoveItemsFromWishlistsRequest
        //private WishlistBulkRemoveItemsFromWishlistsRequest instance;

        public WishlistBulkRemoveItemsFromWishlistsRequestTests()
        {
            // TODO uncomment below to create an instance of WishlistBulkRemoveItemsFromWishlistsRequest
            //instance = new WishlistBulkRemoveItemsFromWishlistsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistBulkRemoveItemsFromWishlistsRequest
        /// </summary>
        [Fact]
        public void WishlistBulkRemoveItemsFromWishlistsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WishlistBulkRemoveItemsFromWishlistsRequest
            //Assert.IsType<WishlistBulkRemoveItemsFromWishlistsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ItemGrns'
        /// </summary>
        [Fact]
        public void ItemGrnsTest()
        {
            // TODO unit test for the property 'ItemGrns'
        }

        /// <summary>
        /// Test the property 'WishlistIds'
        /// </summary>
        [Fact]
        public void WishlistIdsTest()
        {
            // TODO unit test for the property 'WishlistIds'
        }
    }
}
