/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using wishlist.Client;
using wishlist.Api;
// uncomment below to import models
//using wishlist.Model;

namespace wishlist.Test.Api
{
    /// <summary>
    ///  Class for testing WishlistApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WishlistApiTests : IDisposable
    {
        private WishlistApi instance;

        public WishlistApiTests()
        {
            instance = new WishlistApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WishlistApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WishlistApi
            //Assert.IsType<WishlistApi>(instance);
        }

        /// <summary>
        /// Test WishlistAddItemToWishlist
        /// </summary>
        [Fact]
        public void WishlistAddItemToWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistAddItemToWishlistRequest body = null;
            //var response = instance.WishlistAddItemToWishlist(body);
            //Assert.IsType<WishlistWishlistItemResponse>(response);
        }

        /// <summary>
        /// Test WishlistAreItemsInWishlists
        /// </summary>
        [Fact]
        public void WishlistAreItemsInWishlistsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistAreItemsInWishlistsRequest body = null;
            //var response = instance.WishlistAreItemsInWishlists(body);
            //Assert.IsType<WishlistAreItemsInWishlistsResponse>(response);
        }

        /// <summary>
        /// Test WishlistBulkCreateSharing
        /// </summary>
        [Fact]
        public void WishlistBulkCreateSharingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistBulkCreateSharingRequest body = null;
            //var response = instance.WishlistBulkCreateSharing(body);
            //Assert.IsType<WishlistBulkCreateSharingResponse>(response);
        }

        /// <summary>
        /// Test WishlistBulkRemoveItemsFromWishlists
        /// </summary>
        [Fact]
        public void WishlistBulkRemoveItemsFromWishlistsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistBulkRemoveItemsFromWishlistsRequest body = null;
            //var response = instance.WishlistBulkRemoveItemsFromWishlists(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WishlistBulkRevokeSharing
        /// </summary>
        [Fact]
        public void WishlistBulkRevokeSharingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistBulkRevokeSharingRequest body = null;
            //var response = instance.WishlistBulkRevokeSharing(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WishlistCreateWishlist
        /// </summary>
        [Fact]
        public void WishlistCreateWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistCreateWishlistRequest body = null;
            //var response = instance.WishlistCreateWishlist(body);
            //Assert.IsType<WishlistWishlistResponse>(response);
        }

        /// <summary>
        /// Test WishlistDeleteWishlist
        /// </summary>
        [Fact]
        public void WishlistDeleteWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistDeleteWishlistRequest body = null;
            //var response = instance.WishlistDeleteWishlist(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WishlistGetItemFromWishlist
        /// </summary>
        [Fact]
        public void WishlistGetItemFromWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistGetItemFromWishlistRequest body = null;
            //var response = instance.WishlistGetItemFromWishlist(body);
            //Assert.IsType<WishlistWishlistItemResponse>(response);
        }

        /// <summary>
        /// Test WishlistGetWishlistById
        /// </summary>
        [Fact]
        public void WishlistGetWishlistByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistGetWishlistByIdRequest body = null;
            //var response = instance.WishlistGetWishlistById(body);
            //Assert.IsType<WishlistWishlistResponse>(response);
        }

        /// <summary>
        /// Test WishlistGetWishlistBySharedCode
        /// </summary>
        [Fact]
        public void WishlistGetWishlistBySharedCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistGetWishlistBySharedCodeRequest body = null;
            //var response = instance.WishlistGetWishlistBySharedCode(body);
            //Assert.IsType<WishlistWishlistResponse>(response);
        }

        /// <summary>
        /// Test WishlistListWishlistItems
        /// </summary>
        [Fact]
        public void WishlistListWishlistItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistListWishlistItemsRequest body = null;
            //var response = instance.WishlistListWishlistItems(body);
            //Assert.IsType<WishlistListWishlistItemsResponse>(response);
        }

        /// <summary>
        /// Test WishlistListWishlists
        /// </summary>
        [Fact]
        public void WishlistListWishlistsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistListWishlistsRequest body = null;
            //var response = instance.WishlistListWishlists(body);
            //Assert.IsType<WishlistListWishlistsResponse>(response);
        }

        /// <summary>
        /// Test WishlistMergeWishlists
        /// </summary>
        [Fact]
        public void WishlistMergeWishlistsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistMergeWishlistsRequest body = null;
            //var response = instance.WishlistMergeWishlists(body);
            //Assert.IsType<WishlistWishlistResponse>(response);
        }

        /// <summary>
        /// Test WishlistRemoveItemFromWishlist
        /// </summary>
        [Fact]
        public void WishlistRemoveItemFromWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistRemoveItemFromWishlistRequest body = null;
            //var response = instance.WishlistRemoveItemFromWishlist(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WishlistUpdateItemInWishlist
        /// </summary>
        [Fact]
        public void WishlistUpdateItemInWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistUpdateItemInWishlistRequest body = null;
            //var response = instance.WishlistUpdateItemInWishlist(body);
            //Assert.IsType<WishlistWishlistItemResponse>(response);
        }

        /// <summary>
        /// Test WishlistUpdateWishlist
        /// </summary>
        [Fact]
        public void WishlistUpdateWishlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WishlistUpdateWishlistRequest body = null;
            //var response = instance.WishlistUpdateWishlist(body);
            //Assert.IsType<WishlistWishlistResponse>(response);
        }
    }
}
