/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = wishlist.Client.OpenAPIDateConverter;

namespace wishlist.Model
{
    /// <summary>
    /// ListWishlistsRequestFilter
    /// </summary>
    [DataContract(Name = "ListWishlistsRequestFilter")]
    public partial class ListWishlistsRequestFilter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListWishlistsRequestFilter" /> class.
        /// </summary>
        /// <param name="customerGrn">If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field..</param>
        public ListWishlistsRequestFilter(string customerGrn = default(string))
        {
            this.CustomerGrn = customerGrn;
        }

        /// <summary>
        /// If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field.
        /// </summary>
        /// <value>If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field.</value>
        [DataMember(Name = "customerGrn", EmitDefaultValue = false)]
        public string CustomerGrn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListWishlistsRequestFilter {\n");
            sb.Append("  CustomerGrn: ").Append(CustomerGrn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
