/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = wishlist.Client.OpenAPIDateConverter;

namespace wishlist.Model
{
    /// <summary>
    /// WishlistWishlistItemResponse
    /// </summary>
    [DataContract(Name = "wishlistWishlistItemResponse")]
    public partial class WishlistWishlistItemResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WishlistWishlistItemResponse" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="grn">grn.</param>
        /// <param name="wishlistId">wishlistId.</param>
        /// <param name="itemGrn">itemGrn.</param>
        /// <param name="preferredQuantity">preferredQuantity.</param>
        /// <param name="description">description.</param>
        /// <param name="addedByCustomerGrn">addedByCustomerGrn.</param>
        /// <param name="addedAt">addedAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public WishlistWishlistItemResponse(string id = default(string), string grn = default(string), string wishlistId = default(string), string itemGrn = default(string), string preferredQuantity = default(string), WishlistLocalizedText description = default(WishlistLocalizedText), string addedByCustomerGrn = default(string), DateTime addedAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.Id = id;
            this.Grn = grn;
            this.WishlistId = wishlistId;
            this.ItemGrn = itemGrn;
            this.PreferredQuantity = preferredQuantity;
            this.Description = description;
            this.AddedByCustomerGrn = addedByCustomerGrn;
            this.AddedAt = addedAt;
            this.UpdatedAt = updatedAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Grn
        /// </summary>
        [DataMember(Name = "grn", EmitDefaultValue = false)]
        public string Grn { get; set; }

        /// <summary>
        /// Gets or Sets WishlistId
        /// </summary>
        [DataMember(Name = "wishlistId", EmitDefaultValue = false)]
        public string WishlistId { get; set; }

        /// <summary>
        /// Gets or Sets ItemGrn
        /// </summary>
        [DataMember(Name = "itemGrn", EmitDefaultValue = false)]
        public string ItemGrn { get; set; }

        /// <summary>
        /// Gets or Sets PreferredQuantity
        /// </summary>
        [DataMember(Name = "preferredQuantity", EmitDefaultValue = false)]
        public string PreferredQuantity { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public WishlistLocalizedText Description { get; set; }

        /// <summary>
        /// Gets or Sets AddedByCustomerGrn
        /// </summary>
        [DataMember(Name = "addedByCustomerGrn", EmitDefaultValue = false)]
        public string AddedByCustomerGrn { get; set; }

        /// <summary>
        /// Gets or Sets AddedAt
        /// </summary>
        [DataMember(Name = "addedAt", EmitDefaultValue = false)]
        public DateTime AddedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WishlistWishlistItemResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Grn: ").Append(Grn).Append("\n");
            sb.Append("  WishlistId: ").Append(WishlistId).Append("\n");
            sb.Append("  ItemGrn: ").Append(ItemGrn).Append("\n");
            sb.Append("  PreferredQuantity: ").Append(PreferredQuantity).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AddedByCustomerGrn: ").Append(AddedByCustomerGrn).Append("\n");
            sb.Append("  AddedAt: ").Append(AddedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
