/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = wishlist.Client.OpenAPIDateConverter;

namespace wishlist.Model
{
    /// <summary>
    /// Defines wishlistPermission
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WishlistPermission
    {
        /// <summary>
        /// Enum UNKNOWNPERMISSION for value: UNKNOWN_PERMISSION
        /// </summary>
        [EnumMember(Value = "UNKNOWN_PERMISSION")]
        UNKNOWNPERMISSION = 1,

        /// <summary>
        /// Enum VIEWPERMISSION for value: VIEW_PERMISSION
        /// </summary>
        [EnumMember(Value = "VIEW_PERMISSION")]
        VIEWPERMISSION = 2,

        /// <summary>
        /// Enum EDITPERMISSION for value: EDIT_PERMISSION
        /// </summary>
        [EnumMember(Value = "EDIT_PERMISSION")]
        EDITPERMISSION = 3
    }

}
