/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = wishlist.Client.OpenAPIDateConverter;

namespace wishlist.Model
{
    /// <summary>
    /// WishlistAreItemsInWishlistsResponsePayload
    /// </summary>
    [DataContract(Name = "wishlistAreItemsInWishlistsResponsePayload")]
    public partial class WishlistAreItemsInWishlistsResponsePayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WishlistAreItemsInWishlistsResponsePayload" /> class.
        /// </summary>
        /// <param name="wishlistGrnToWishlistItemGrnMap">wishlistGrnToWishlistItemGrnMap.</param>
        public WishlistAreItemsInWishlistsResponsePayload(Dictionary<string, string> wishlistGrnToWishlistItemGrnMap = default(Dictionary<string, string>))
        {
            this.WishlistGrnToWishlistItemGrnMap = wishlistGrnToWishlistItemGrnMap;
        }

        /// <summary>
        /// Gets or Sets WishlistGrnToWishlistItemGrnMap
        /// </summary>
        [DataMember(Name = "wishlistGrnToWishlistItemGrnMap", EmitDefaultValue = false)]
        public Dictionary<string, string> WishlistGrnToWishlistItemGrnMap { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WishlistAreItemsInWishlistsResponsePayload {\n");
            sb.Append("  WishlistGrnToWishlistItemGrnMap: ").Append(WishlistGrnToWishlistItemGrnMap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
