/*
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = wishlist.Client.OpenAPIDateConverter;

namespace wishlist.Model
{
    /// <summary>
    /// WishlistBulkCreateSharingResponse
    /// </summary>
    [DataContract(Name = "wishlistBulkCreateSharingResponse")]
    public partial class WishlistBulkCreateSharingResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WishlistBulkCreateSharingResponse" /> class.
        /// </summary>
        /// <param name="sharingResponses">sharingResponses.</param>
        public WishlistBulkCreateSharingResponse(List<WishlistSharingResponse> sharingResponses = default(List<WishlistSharingResponse>))
        {
            this.SharingResponses = sharingResponses;
        }

        /// <summary>
        /// Gets or Sets SharingResponses
        /// </summary>
        [DataMember(Name = "sharingResponses", EmitDefaultValue = false)]
        public List<WishlistSharingResponse> SharingResponses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WishlistBulkCreateSharingResponse {\n");
            sb.Append("  SharingResponses: ").Append(SharingResponses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
